server:
  port: 8090

spring:
  application:
    name: resource-api
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

ural:
  application:
    threadpool:
      name: ural
      corePoolSize: 20
      maximumPoolSize: 50
      keepAliveTime: 60
      maxWaitTime: 60
      queueSize: 1000


